name: ${project.name}
description: ${project.description}
version: ${project.version}
main: ${main.class}
author: ${author}
api-version: 1.13
folia-supported: true
depend: [LuckPerms]
softdepend: [PlaceholderAPI]
commands:
  lpc:
    description: Reload the configuration.
    permission: lpc.reload
    usage: "Usage: /lpc reload"
